### ISSUE TITLE
Not able to pass file name as regex in npx npx github-actions-ctrf command

### ISSUE THREAD

**Issue by lalitsvm** [ctrf-io/github-actions-test-reporter-ctrf#4]
@Ma11hewThomas I am using Windows OS and electron project for WebdriverIO. I am able to generate ctrf file which is having format **ctrf/ctrf-report-end-to-end-login.spec-2024-07-05T05-57-42-778Z.json**.

I want to use command like  npx github-actions-ctrf **ctrf/ctrf-report-*.json** but i am getting error _Failed to read file: Error: ENOENT: no such file or directory, open 'ctrf/ctrf-report-*.json'_ 

I also tried to fix file name by using below option but it didn't generate file name as _ctrf-report.json_ but still generating file name as _ctrf-report-end-to-end-login.spec-2024-07-05T05-57-42-778Z.json_

reporters: [
		
		['ctrf-json',
			{
				outputFile: 'ctrf-report.json',
				outputDir: 'ctrf',
			}
		]

	],

Please suggest.

**Comment by Ma11hewThomas** [comment]
Hi @lalitsvm,
Currently this package only supports a single ctrf report. 

Due to the architecture of WDIO, the filename can not be defined, you have two options - 

If running in parallel and generating multiple ctrf reports:
The [ctrf-cli](https://github.com/ctrf-io/ctrf-cli) package provides a method to merge the multiple json files into a single file and you can state the file name.

If always generating a single report, use a bash script or similar to find and rename the file. 

Thanks
